n = str(input('Digite seu nome completo: ')).strip()
nome = n.split()
print('Nice to met you my friend !')
print('Seu primeiro nome é {}'.format(nome[0]))
print('Seu ultimo nome é {}'.format(nome[-1]))